function love.load()
  print("div", 10 / 2)
  print("fmt", string.format("%d", 3.0))
  print("unpack", unpack({ 1, 2, 3 }))
  print("random", love.math.random(3, 3), love.math.random(1))
  love.math.setRandomSeed(42)
  local a = love.math.random()
  love.math.setRandomSeed(42)
  print("seed", a == love.math.random(), love.math.getRandomSeed())
  print("write", love.filesystem.write("t.txt", "abc\ndef\n"))
  print("read", love.filesystem.read("t.txt"))
  print("info", love.filesystem.getInfo("t.txt").size, love.filesystem.getInfo("nope"))
  for l in love.filesystem.lines("t.txt") do print("line", l) end
  print("require", require("lib.util").v)
  print("load", love.filesystem.load("lib/util.lua")().v)
  print("items", table.concat(love.filesystem.getDirectoryItems("lib"), ","))
  print("safe", love.filesystem.read("../secret"))
  local ok, err = pcall(function() return love.graphics.newShader("x") end)
  print("shader", ok, err)
  print("joy", love.joystick.getJoystickCount(), love.joystick.getJoysticks()[1]:isGamepad())
  print("version", love.getVersion())
  print("os", love.system.getOS())
  local ok2, err2 = pcall(love.graphics.pop)
  print("pop", ok2, err2)
  love.event.push("custom", 1, "deux")
  love.event.quit(0)
end
